name: Sincronizacion Directa Google-GitHub

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Descargar CSV de Google Sheets
        run: |
          wget --no-check-certificate --output-document=Exportar_Nutricion.csv "https://docs.google.com/spreadsheets/d/1SVngRRAcMq9Jn3ZSH0tGqI4cTbytCcidI2ESQ6LEgXs/edit?usp=sharing"

      - name: Guardar en GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Exportar_Nutricion.csv
          git commit -m "Actualización de datos maestros: $(date)" || exit 0
          git push
