name: Sincronizacion Directa Google-GitHub

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Descargar CSV de Google Sheets
        run: |
          curl -sSL "https://docs.google.com/spreadsheets/d/e/2PACX-1vST5tQDJLdinNhkOJZOWV9RbTYP0qZCyj2qcLBHnfDU_RdJeGgTNVmBQQ6VM-PwqvyzrgTCMc_Gyp1U/pub?gid=554583428&single=true&output=csv" -o Exportar_Nutricion.csv

      - name: Guardar en GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Exportar_Nutricion.csv
          git commit -m "Sincronización limpia forzada" || exit 0
          git push
