name: Actualizar CSV desde Google

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Descargar datos de Google Sheets
        run: |
          wget --no-check-certificate --output-document=Exportar_Nutricion.csv "https://script.google.com/macros/s/AKfycbzT88obTu0hGX-ccdEMhD4c0xbRxYVJxcRQa3Yc0O60diqp4CcgqZKPMjJZc1w7bHY/exec"

      - name: Guardar en GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Exportar_Nutricion.csv
          git commit -m "Sincronización limpia de datos" || exit 0
          git push
