name: Update Exportar_Nutricion.csv from Google Sheets

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora
  workflow_dispatch: # Permite ejecución manual

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download CSV from Google Sheets
        run: |
          curl -sSL "https://docs.google.com/spreadsheets/d/e/2PACX-1vST5tQDJLdinNhkOJZOWV9RbTYP0qZCyj2qcLBHnfDU_RdJeGgTNVmBQQ6VM-PwqvyzrgTCMc_Gyp1U/pub?gid=554583428&single=true&output=csv" -o Exportar_Nutricion.csv

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- Exportar_Nutricion.csv; then
            git add Exportar_Nutricion.csv
            git commit -m "Update Exportar_Nutricion.csv from Google Sheets"
            git push
          else
            echo "No changes"
          fi
