name: Actualizar CSV desde Google

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta automáticamente cada hora
  workflow_dispatch: # Permite que tú lo ejecutes manualmente con el botón gris

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Descargar datos de Google Sheets
        run: |
          curl -L "https://script.google.com/macros/s/AKfycbzT88obTu0hGX-ccdEMhD4c0xbRxYVJxcRQa3Yc0O60diqp4CcgqZKPMjJZc1w7bHY/exec" -o Exportar_Nutricion.csv

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Exportar_Nutricion.csv
          git commit -m "Sincronización automática de potreros" || exit 0
          git push
